//! Light power estimates: what a smart bulb draws, from its state and its
//! model's measured profile (brightness, white or colour; standby when
//! off; nothing when it has no power). Never a measure: an appliance meter
//! with `estimate = true` (shown « ≈ », never added to a total).
//!
//! The profiles come from powercalc, whose contributors measured each model
//! with a plug meter (`scripts/light-profiles.py` condenses them). MIT,
//! (c) 2021 Bram Gerritsen: see `NOTICE` and `licenses/powercalc-MIT.txt`.

use moli_core::{DeviceId, Kind, Semantic, Unit, Value};
use moli_runtime::{DeviceView, Hub};

/// One bulb model: watts by brightness (at [`STEPS`] out of 255), in white
/// and in colour, and on standby.
#[derive(Debug)]
pub(crate) struct Profile {
    pub models: &'static [&'static str],
    #[allow(dead_code)]
    pub name: &'static str,
    pub standby: f64,
    pub white: [f64; 17],
    pub colour: [f64; 17],
}

// Generated by scripts/light-profiles.py from powercalc's measured profiles
// (github.com/bramstroker/homeassistant-powercalc, MIT licence).
pub(crate) const STEPS: [u8; 17] = [
    1, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 255,
];
pub(crate) const PROFILES: &[Profile] = &[
    Profile {
        models: &["LCA006", "9290024688", "9290024689"],
        name: "Hue White and Color Ambiance E27/B22 1100lm with BT",
        standby: 0.4,
        white: [
            1.08, 1.07, 1.11, 1.24, 1.38, 1.6, 1.85, 2.13, 2.53, 2.9, 3.4, 3.9, 4.43, 5.11, 5.79,
            6.65, 7.3,
        ],
        colour: [
            1.03, 1.08, 1.1, 1.18, 1.35, 1.51, 1.71, 1.94, 2.22, 2.66, 3.0, 3.4, 3.81, 4.22, 4.75,
            5.14, 5.43,
        ],
    },
    Profile {
        models: &["LTW001", "8718696548738"],
        name: "Hue White Ambiance A19",
        standby: 0.4,
        white: [
            1.48, 1.47, 1.59, 1.7, 1.92, 2.1, 2.38, 2.72, 3.13, 3.58, 4.0, 4.51, 5.13, 5.75, 6.53,
            7.38, 7.95,
        ],
        colour: [
            1.48, 1.47, 1.59, 1.7, 1.92, 2.1, 2.38, 2.72, 3.13, 3.58, 4.0, 4.51, 5.13, 5.75, 6.53,
            7.38, 7.95,
        ],
    },
    Profile {
        models: &["LWA017", "9290024692", "929002469202"],
        name: "Hue White Bulb A60 E27 1050lm with Bluetooth",
        standby: 0.42,
        white: [
            1.11, 1.24, 1.34, 1.54, 1.83, 2.21, 2.58, 3.04, 3.51, 4.1, 4.63, 5.49, 6.32, 7.04,
            7.98, 9.1, 10.19,
        ],
        colour: [
            1.11, 1.24, 1.34, 1.54, 1.83, 2.21, 2.58, 3.04, 3.51, 4.1, 4.63, 5.49, 6.32, 7.04,
            7.98, 9.1, 10.19,
        ],
    },
    Profile {
        models: &["L530"],
        name: "Tapo Smart Wi-Fi Light Bulb, Multicolor",
        standby: 0.4,
        white: [
            0.72, 1.02, 1.4, 1.9, 2.31, 2.77, 3.16, 3.53, 3.97, 4.41, 4.9, 5.26, 5.71, 6.17, 6.57,
            7.01, 7.35,
        ],
        colour: [
            0.59, 0.59, 1.5, 1.5, 2.14, 2.14, 2.63, 2.63, 3.09, 3.09, 3.65, 3.65, 4.35, 4.35, 4.96,
            4.96, 5.53,
        ],
    },
];

fn profile_of(model: &str) -> Option<&'static Profile> {
    PROFILES.iter().find(|p| {
        p.models
            .iter()
            .any(|m| m.eq_ignore_ascii_case(model.trim()))
    })
}

/// Watts along a curve at `bri` (0–255), between its measured steps.
fn along(curve: &[f64; 17], bri: f64) -> f64 {
    let bri = bri.clamp(1.0, 255.0);
    let i = STEPS
        .iter()
        .rposition(|s| f64::from(*s) <= bri)
        .unwrap_or(0);
    if i + 1 >= STEPS.len() {
        return curve[STEPS.len() - 1];
    }
    let (a, b) = (f64::from(STEPS[i]), f64::from(STEPS[i + 1]));
    curve[i] + (curve[i + 1] - curve[i]) * (bri - a) / (b - a)
}

fn truthy(v: &Value) -> bool {
    match v {
        Value::Bool(b) => *b,
        Value::Int(i) => *i != 0,
        Value::Text(t) => t.eq_ignore_ascii_case("on") || t.eq_ignore_ascii_case("true"),
        _ => false,
    }
}

/// What one bulb draws now (W), if its model is known.
fn bulb(view: &DeviceView) -> Option<f64> {
    let profile = profile_of(view.device.model.as_deref()?)?;
    // No answer, no power: a wall switch cut it.
    if view.online == Some(false) {
        return Some(0.0);
    }
    let get = |semantic: Semantic| {
        let p = view.device.points.iter().find(|p| p.semantic == semantic)?;
        Some((p, view.state.get(&p.key).map(|s| &s.value)?))
    };
    let on = get(Semantic::OnOff).is_some_and(|(_, v)| truthy(v));
    if !on {
        return Some(profile.standby);
    }
    let pct = get(Semantic::Brightness)
        .and_then(|(p, v)| {
            let raw = v.as_f64()?;
            Some(match (&p.unit, &p.kind) {
                (Some(Unit::Percent), _) => raw,
                (_, Kind::Numeric { max: Some(max), .. }) if *max > 0.0 => raw * 100.0 / max,
                _ => raw,
            })
        })
        .unwrap_or(100.0);
    // A Hue bulb in colour has no white temperature.
    let colour = get(Semantic::Color).is_some()
        && view
            .device
            .points
            .iter()
            .any(|p| p.semantic == Semantic::ColorTemp)
        && get(Semantic::ColorTemp).is_none_or(|(_, v)| matches!(v, Value::Null));
    let curve = if colour {
        &profile.colour
    } else {
        &profile.white
    };
    Some(along(curve, pct * 2.55))
}

/// What a light draws now (W): a bulb by its profile, a fixture
/// (`lumieres:…`) by its bulbs'. None when no model is known.
pub(crate) fn watts(hub: &Hub, device: &DeviceId) -> Option<f64> {
    let view = hub.device(device)?;
    if view.device.model.as_deref() == Some("Luminaire") {
        let parts: Vec<f64> = view
            .device
            .members
            .iter()
            .filter_map(|m| hub.device(m).as_ref().and_then(bulb))
            .collect();
        return (!parts.is_empty()).then(|| parts.iter().sum());
    }
    bulb(&view)
}

/// The devices whose state moves a light's estimate: itself, and a
/// fixture's members.
pub(crate) fn sources(hub: &Hub, device: &DeviceId) -> Vec<DeviceId> {
    let mut out = vec![device.clone()];
    if let Some(view) = hub.device(device) {
        out.extend(view.device.members.iter().cloned());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn curves_read_between_their_steps() {
        let lca = profile_of("LCA006").unwrap();
        assert!((along(&lca.white, 255.0) - 7.3).abs() < 1e-9, "full white");
        assert!((along(&lca.white, 1.0) - 1.08).abs() < 1e-9);
        let mid = along(&lca.white, 136.0);
        assert!(
            mid > lca.white[8] && mid < lca.white[9],
            "between 128 and 144"
        );
        assert!(
            profile_of("9290024689").is_some(),
            "by its product number too"
        );
        assert!(profile_of("CK-BL702-AL-01").is_none(), "unknown: no guess");
        for p in PROFILES {
            assert!(
                p.white.windows(2).all(|w| w[1] >= w[0] - 0.2),
                "{}: brighter draws more",
                p.name
            );
        }
    }
}
