// A hand-picked set of Material Design Icons (the ones Home Assistant
// uses): only these end up in the bundle.
import { t } from '../../lib/i18n.svelte.js';
import {
  mdiCeilingLight,
  mdiCeilingFanLight,
  mdiFloorLamp,
  mdiLamp,
  mdiSpotlightBeam,
  mdiPowerSocketEu,
  mdiWallSconceFlat,
  mdiLedStripVariant,
  mdiPalmTree,
  mdiPrinter,
  mdiServer,
  mdiHarddisk,
  mdiMemory,
  mdiChip,
  mdiDocker,
  mdiDesktopTowerMonitor,
  mdiLan,
  mdiPrinter3d,
  mdiPrinter3dNozzle,
  mdiStop,
  mdiBookOpenVariant,
  mdiCandle,
  mdiHeart,
  mdiMovieOpen,
  mdiPalette,
  mdiPartyPopper,
  mdiPineTree,
  mdiStarFourPoints,
  mdiWaves,
  mdiAccountOutline,
  mdiWifiOff,
  mdiAlertOutline,
  mdiArrowLeft,
  mdiAutoFix,
  mdiBellOutline,
  mdiCheckCircleOutline,
  mdiClockOutline,
  mdiCloseCircleOutline,
  mdiContentSaveOutline,
  mdiCreation,
  mdiFitToScreenOutline,
  mdiFlaskOutline,
  mdiGestureTapButton,
  mdiHistory,
  mdiMagnifyMinusOutline,
  mdiMagnifyPlusOutline,
  mdiPlayCircleOutline,
  mdiPlus,
  mdiRepeat,
  mdiRobotOutline,
  mdiShieldCheckOutline,
  mdiSourceBranch,
  mdiSwapHorizontal,
  mdiTimerOutline,
  mdiTrashCanOutline,
  mdiAirConditioner,
  mdiAlertCircleOutline,
  mdiArrowTopRight,
  mdiBedKingOutline,
  mdiBedOutline,
  mdiBellRingOutline,
  mdiCameraOutline,
  mdiCarOutline,
  mdiCctv,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiDeskLamp,
  mdiDogSide,
  mdiDoor,
  mdiDoorClosed,
  mdiDoorOpen,
  mdiDotsHorizontal,
  mdiFan,
  mdiFire,
  mdiFlash,
  mdiFlowerOutline,
  mdiGate,
  mdiHomeOutline,
  mdiHomeRoof,
  mdiInformationOutline,
  mdiKeyboardOutline,
  mdiLeaf,
  mdiLightbulbGroupOutline,
  mdiLightbulbOutline,
  mdiLightningBolt,
  mdiLock,
  mdiMicrophoneOutline,
  mdiAccountVoice,
  mdiPhoneHangup,
  mdiMonitorDashboard,
  mdiMoonWaningCrescent,
  mdiMotionSensor,
  mdiPackageVariantClosed,
  mdiPause,
  mdiPlay,
  mdiPlayPause,
  mdiPool,
  mdiPower,
  mdiRemoteTv,
  mdiSend,
  mdiShowerHead,
  mdiSilverwareForkKnife,
  mdiSkipNext,
  mdiSkipPrevious,
  mdiSnowflake,
  mdiSofaOutline,
  mdiSpeaker,
  mdiStairs,
  mdiSunAngle,
  mdiTelevision,
  mdiTelevisionAmbientLight,
  mdiThermometer,
  mdiToilet,
  mdiTune,
  mdiUndoVariant,
  mdiVolumeHigh,
  mdiVolumeMinus,
  mdiVolumeOff,
  mdiVolumePlus,
  mdiWaterOutline,
  mdiWaterPercent,
  mdiWeatherCloudy,
  mdiWeatherFog,
  mdiWeatherLightningRainy,
  mdiWeatherNight,
  mdiWeatherPartlyCloudy,
  mdiWeatherPouring,
  mdiWeatherRainy,
  mdiWeatherSnowy,
  mdiWeatherSunny,
  mdiWeatherSunset,
  mdiWeatherSunsetUp,
  mdiWeatherWindy,
  mdiWhiteBalanceSunny,
  mdiWindowShutter,
} from '@mdi/js';

/** Names used by the layout (home.json) and the pages. */
export const icons = {
  'ceiling-light': mdiCeilingLight,
  'ceiling-fan-light': mdiCeilingFanLight,
  'floor-lamp': mdiFloorLamp,
  lamp: mdiLamp,
  spotlight: mdiSpotlightBeam,
  socket: mdiPowerSocketEu,
  'tv-light': mdiTelevisionAmbientLight,
  sconce: mdiWallSconceFlat,
  'led-strip': mdiLedStripVariant,
  printer: mdiPrinter,
  server: mdiServer,
  harddisk: mdiHarddisk,
  memory: mdiMemory,
  chip: mdiChip,
  docker: mdiDocker,
  computer: mdiDesktopTowerMonitor,
  lan: mdiLan,
  printer3d: mdiPrinter3d,
  nozzle: mdiPrinter3dNozzle,
  stop: mdiStop,
  book: mdiBookOpenVariant,
  candle: mdiCandle,
  heart: mdiHeart,
  movie: mdiMovieOpen,
  palette: mdiPalette,
  party: mdiPartyPopper,
  pine: mdiPineTree,
  stars: mdiStarFourPoints,
  waves: mdiWaves,
  warning: mdiAlertOutline,
  'arrow-left': mdiArrowLeft,
  magic: mdiAutoFix,
  'bell-outline': mdiBellOutline,
  ok: mdiCheckCircleOutline,
  clock: mdiClockOutline,
  ko: mdiCloseCircleOutline,
  save: mdiContentSaveOutline,
  sparkles: mdiCreation,
  fit: mdiFitToScreenOutline,
  flask: mdiFlaskOutline,
  hand: mdiGestureTapButton,
  history: mdiHistory,
  offline: mdiWifiOff,
  'zoom-out': mdiMagnifyMinusOutline,
  'zoom-in': mdiMagnifyPlusOutline,
  'play-circle': mdiPlayCircleOutline,
  plus: mdiPlus,
  repeat: mdiRepeat,
  robot: mdiRobotOutline,
  shield: mdiShieldCheckOutline,
  branch: mdiSourceBranch,
  swap: mdiSwapHorizontal,
  timer: mdiTimerOutline,
  trash: mdiTrashCanOutline,
  account: mdiAccountOutline,
  'air-conditioner': mdiAirConditioner,
  alert: mdiAlertCircleOutline,
  'arrow-top-right': mdiArrowTopRight,
  'bed-king-outline': mdiBedKingOutline,
  'bed-outline': mdiBedOutline,
  bell: mdiBellRingOutline,
  camera: mdiCameraOutline,
  car: mdiCarOutline,
  cctv: mdiCctv,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  close: mdiClose,
  'desk-lamp': mdiDeskLamp,
  dog: mdiDogSide,
  door: mdiDoor,
  'door-closed': mdiDoorClosed,
  'door-open': mdiDoorOpen,
  dots: mdiDotsHorizontal,
  fan: mdiFan,
  fire: mdiFire,
  flash: mdiFlash,
  'flower-outline': mdiFlowerOutline,
  gate: mdiGate,
  home: mdiHomeOutline,
  'home-roof': mdiHomeRoof,
  info: mdiInformationOutline,
  keyboard: mdiKeyboardOutline,
  leaf: mdiLeaf,
  'light-group': mdiLightbulbGroupOutline,
  light: mdiLightbulbOutline,
  bolt: mdiLightningBolt,
  lock: mdiLock,
  mic: mdiMicrophoneOutline,
  talk: mdiAccountVoice,
  hangup: mdiPhoneHangup,
  atelier: mdiMonitorDashboard,
  moon: mdiMoonWaningCrescent,
  motion: mdiMotionSensor,
  package: mdiPackageVariantClosed,
  pause: mdiPause,
  play: mdiPlay,
  'play-pause': mdiPlayPause,
  pool: mdiPool,
  power: mdiPower,
  remote: mdiRemoteTv,
  send: mdiSend,
  'shower-head': mdiShowerHead,
  'silverware-fork-knife': mdiSilverwareForkKnife,
  next: mdiSkipNext,
  previous: mdiSkipPrevious,
  snowflake: mdiSnowflake,
  sofa: mdiSofaOutline,
  'sofa-outline': mdiSofaOutline,
  speaker: mdiSpeaker,
  stairs: mdiStairs,
  'sun-angle': mdiSunAngle,
  tv: mdiTelevision,
  ambilight: mdiTelevisionAmbientLight,
  thermometer: mdiThermometer,
  toilet: mdiToilet,
  tune: mdiTune,
  back: mdiUndoVariant,
  'volume-high': mdiVolumeHigh,
  'volume-minus': mdiVolumeMinus,
  'volume-off': mdiVolumeOff,
  'volume-plus': mdiVolumePlus,
  water: mdiWaterOutline,
  humidity: mdiWaterPercent,
  sunset: mdiWeatherSunset,
  sunrise: mdiWeatherSunsetUp,
  wind: mdiWeatherWindy,
  sun: mdiWhiteBalanceSunny,
  palm: mdiPalmTree,
  shutter: mdiWindowShutter,
};

export const icon = (name) => icons[name] ?? mdiLightbulbOutline;

/** WMO weather code (Open-Meteo) → icon and words (said in the house's
 *  language when called, not when the module loads). */
export function weatherOf(code, day = true) {
  const c = Number(code);
  if (!Number.isFinite(c)) return { icon: mdiWeatherCloudy, label: t('commun.meteo.indisponible') };
  if (c === 0) return { icon: day ? mdiWeatherSunny : mdiWeatherNight, label: t('commun.meteo.degage') };
  if (c <= 2) return { icon: day ? mdiWeatherPartlyCloudy : mdiWeatherNight, label: t('commun.meteo.quelques_nuages') };
  if (c === 3) return { icon: mdiWeatherCloudy, label: t('commun.meteo.couvert') };
  if (c <= 48) return { icon: mdiWeatherFog, label: t('commun.meteo.brouillard') };
  if (c <= 57) return { icon: mdiWeatherRainy, label: t('commun.meteo.bruine') };
  if (c <= 64 || (c >= 80 && c <= 81)) return { icon: mdiWeatherRainy, label: t('commun.meteo.pluie') };
  if (c <= 67 || c === 82) return { icon: mdiWeatherPouring, label: t('commun.meteo.forte_pluie') };
  if (c <= 77 || c === 85 || c === 86) return { icon: mdiWeatherSnowy, label: t('commun.meteo.neige') };
  return { icon: mdiWeatherLightningRainy, label: t('commun.meteo.orage') };
}
