#!/usr/bin/env python3
"""Light power profiles for Moli's estimates, from powercalc's measured LUTs.

powercalc (github.com/bramstroker/homeassistant-powercalc, MIT licence)
measures each bulb model with a plug meter: watts by brightness, white
temperature and colour. Home Assistant keeps the profiles it downloaded under
`.storage/powercalc_profiles/<maker>/<model>/`. This script condenses each
into two curves (white, colour: watts by brightness, averaged over the
temperatures and hues) and prints the Rust table of
`crates/moli-energy/src/estimate.rs`.

    sudo python3 scripts/light-profiles.py <powercalc_profiles dir> signify/LCA006 … > table.rs
"""
import csv
import gzip
import json
import pathlib
import sys

STEPS = [1, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 255]


def rows(path):
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt") as f:
        yield from csv.DictReader(f)


def curve(path):
    """Watts by brightness (0–255), averaged over the other columns."""
    sums, counts = {}, {}
    for r in rows(path):
        b = int(r["bri"])
        sums[b] = sums.get(b, 0.0) + float(r["watt"])
        counts[b] = counts.get(b, 0) + 1
    known = sorted(sums)
    out = []
    for step in STEPS:
        near = [b for b in known if abs(b - step) <= 8] or [min(known, key=lambda b: abs(b - step))]
        out.append(round(sum(sums[b] for b in near) / sum(counts[b] for b in near), 2))
    return out


def find(folder, name):
    for ext in (".csv", ".csv.gz"):
        p = folder / (name + ext)
        if p.exists():
            return p
    return None


def main():
    root = pathlib.Path(sys.argv[1])
    print("// Generated by scripts/light-profiles.py from powercalc's measured profiles")
    print("// (github.com/bramstroker/homeassistant-powercalc, MIT licence).")
    print(f"pub(crate) const STEPS: [u8; {len(STEPS)}] = {STEPS};")
    print("pub(crate) const PROFILES: &[Profile] = &[")
    for spec in sys.argv[2:]:
        folder = root / spec
        model = json.loads((folder / "model.json").read_text())
        white = find(folder, "color_temp") or find(folder, "brightness")
        colour = find(folder, "hs")
        w = curve(white)
        c = curve(colour) if colour else w
        names = [spec.split("/")[1], *model.get("aliases", [])]
        print("    Profile {")
        print(f"        models: &{json.dumps(names)},")
        print(f"        name: {json.dumps(model.get('name', spec))},")
        print(f"        standby: {float(model.get('standby_power', 0.4))},")
        print(f"        white: {w},")
        print(f"        colour: {c},")
        print("    },")
    print("];")


if __name__ == "__main__":
    main()
